# Generated by Django 3.2.5 on 2021-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_vision_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artvisionuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artvisionuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
